package Vistas;


import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ajgem
 */
public class vLigaEspa extends javax.swing.JFrame {

    /**
     * Creates new form vLigaEspa
     */
    public vLigaEspa() {
        initComponents();
        ligaEspa.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        grupo1 = new javax.swing.ButtonGroup();
        grupo2 = new javax.swing.ButtonGroup();
        grupo3 = new javax.swing.ButtonGroup();
        grupo4 = new javax.swing.ButtonGroup();
        grupo5 = new javax.swing.ButtonGroup();
        grupo6 = new javax.swing.ButtonGroup();
        grupo7 = new javax.swing.ButtonGroup();
        grupo8 = new javax.swing.ButtonGroup();
        grupo9 = new javax.swing.ButtonGroup();
        grupo10 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbEspa = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ligaEspa = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        jRadioButton7.setText("1");

        jRadioButton8.setText("X");

        jRadioButton9.setText("2");

        jRadioButton13.setText("1");

        jRadioButton14.setText("X");

        jRadioButton15.setText("2");

        jRadioButton34.setText("2");

        jRadioButton35.setText("X");

        jRadioButton36.setText("1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(54, 54, 54));

        jButton1.setText("GUARDAR");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LIGA ESPAÑOLA");

        cbEspa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JORNADA 1", "JORNADA 2", "JORNADA 3", "JORNADA 4", "JORNADA 5", "JORNADA 6", "JORNADA 7", "JORNADA 8", "JORNADA 9", "JORNADA 10", "JORNADA 11", "JORNADA 12", "JORNADA 13", "JORNADA 14", "JORNADA 15", "JORNADA 16", "JORNADA 17", "JORNADA 18", "JORNADA 19", "JORNADA 20", "JORNADA 21", "JORNADA 22", "JORNADA 23", "JORNADA 24", "JORNADA 25", "JORNADA 26", "JORNADA 27", "JORNADA 28", "JORNADA 29", "JORNADA 30", "JORNADA 31", "JORNADA 32", "JORNADA 33", "JORNADA 34", "JORNADA 35", "JORNADA 36", "JORNADA 37", "JORNADA 38" }));
        cbEspa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspaActionPerformed(evt);
            }
        });

        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ligaEspa.setColumns(20);
        ligaEspa.setRows(5);
        jScrollPane1.setViewportView(ligaEspa);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quiniela Liga Española");

        grupo1.add(jRadioButton1);
        jRadioButton1.setText("1");

        grupo1.add(jRadioButton2);
        jRadioButton2.setText("X");

        grupo1.add(jRadioButton3);
        jRadioButton3.setText("2");

        grupo2.add(jRadioButton4);
        jRadioButton4.setText("1");

        grupo2.add(jRadioButton5);
        jRadioButton5.setText("X");

        grupo2.add(jRadioButton6);
        jRadioButton6.setText("2");

        grupo3.add(jRadioButton10);
        jRadioButton10.setText("1");

        grupo3.add(jRadioButton11);
        jRadioButton11.setText("X");

        grupo3.add(jRadioButton12);
        jRadioButton12.setText("2");

        grupo4.add(jRadioButton17);
        jRadioButton17.setText("X");

        grupo4.add(jRadioButton18);
        jRadioButton18.setText("2");

        grupo4.add(jRadioButton16);
        jRadioButton16.setText("1");

        grupo5.add(jRadioButton19);
        jRadioButton19.setText("X");

        grupo5.add(jRadioButton20);
        jRadioButton20.setText("2");

        grupo5.add(jRadioButton21);
        jRadioButton21.setText("1");

        grupo6.add(jRadioButton22);
        jRadioButton22.setText("X");

        grupo6.add(jRadioButton23);
        jRadioButton23.setText("2");

        grupo6.add(jRadioButton24);
        jRadioButton24.setText("1");

        grupo10.add(jRadioButton37);
        jRadioButton37.setText("2");

        grupo10.add(jRadioButton38);
        jRadioButton38.setText("X");

        grupo10.add(jRadioButton39);
        jRadioButton39.setText("1");

        grupo7.add(jRadioButton25);
        jRadioButton25.setText("2");

        grupo7.add(jRadioButton26);
        jRadioButton26.setText("X");

        grupo7.add(jRadioButton27);
        jRadioButton27.setText("1");

        grupo8.add(jRadioButton28);
        jRadioButton28.setText("2");

        grupo8.add(jRadioButton29);
        jRadioButton29.setText("X");

        grupo8.add(jRadioButton30);
        jRadioButton30.setText("1");

        grupo9.add(jRadioButton31);
        jRadioButton31.setText("2");

        grupo9.add(jRadioButton32);
        jRadioButton32.setText("X");

        grupo9.add(jRadioButton33);
        jRadioButton33.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton37)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton22)
                    .addComponent(jRadioButton23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton27)
                    .addComponent(jRadioButton26)
                    .addComponent(jRadioButton25))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton33)
                    .addComponent(jRadioButton32)
                    .addComponent(jRadioButton31))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton39)
                    .addComponent(jRadioButton38)
                    .addComponent(jRadioButton37)))
        );

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(223, 223, 223)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(388, 388, 388)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(cbEspa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))))))
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(39, 39, 39)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cbEspa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(177, 177, 177)
                    .addComponent(jButton1)
                    .addGap(39, 39, 39)
                    .addComponent(jButton2)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        vQuiniela vn= new vQuiniela();
        vn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbEspaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspaActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) cbEspa.getSelectedItem();
     ligaEspa.setText("");
     if(selectedItem.equals("JORNADA 1")) {
    ligaEspa.append(" Almeria vs Rayo \n\n");
    ligaEspa.append(" Sevilla vs Valencia\n\n");
    ligaEspa.append(" R.Sociedad vs Girona \n\n");
    ligaEspa.append(" Las Palmas vs Mallorca \n\n");
    ligaEspa.append(" Athletic vs Real Madrid \n\n");
    ligaEspa.append(" Celta vs Osasuna \n\n");
    ligaEspa.append(" Villarreal vs Betis \n\n");
    ligaEspa.append(" Getafe vs Barcelona \n\n");
    ligaEspa.append(" Cádiz vs Alavés \n\n");
    ligaEspa.append(" Atlético vs Granada \n\n");
    }
     else if (selectedItem.equals("JORNADA 2")){
         ligaEspa.append(" Mallorca vs Villarreal \n\n");
         ligaEspa.append(" Valencia vs Las Palmas \n\n");
         ligaEspa.append(" R.Sociedad vs Celta    \n\n");
         ligaEspa.append(" Almería vs Real Madrid \n\n");
         ligaEspa.append(" Osasuna vs Athletic    \n\n");
         ligaEspa.append(" Girona vs Getafe       \n\n");
         ligaEspa.append(" Barcelona vs Cádiz     \n\n");
         ligaEspa.append(" Betis vs Atlético      \n\n");
         ligaEspa.append(" Alavés vs Sevilla      \n\n");
         ligaEspa.append(" Granada vs Rayo       \n\n");      
     }
     else if (selectedItem.equals("JORNADA 3")){
         ligaEspa.append(" Las Palmas vs R. Sociedad \n\n");
         ligaEspa.append(" Celta vs Real Madrid\n\n");
         ligaEspa.append(" Cádiz vs Almería \n\n");
         ligaEspa.append(" Granada vs Mallorca \n\n");
         ligaEspa.append(" Sevilla vs Girona \n\n");
         ligaEspa.append(" Villarreal vs Barcelona \n\n");
         ligaEspa.append(" Valencia vs Osasuna \n\n");
         ligaEspa.append(" Athletic vs Betis \n\n");
         ligaEspa.append(" Getafe vs Alavés \n\n");
         ligaEspa.append(" Rayo vs Atlético  \n\n");
        }
     else if (selectedItem.equals("JORNADA 4")){
         ligaEspa.append(" Cádiz vs Villarreal \n\n");
         ligaEspa.append(" Almería vs Celta \n\n");
         ligaEspa.append(" R. Sociedad vs Granada \n\n");
         ligaEspa.append(" Real Madrid vs Getafe \n\n");
         ligaEspa.append(" Alavés vs Valencia \n\n");
         ligaEspa.append(" Betis vs Rayo \n\n");
         ligaEspa.append(" Girona vs Las Palmas \n\n");
         ligaEspa.append(" Mallorca vs Athletic \n\n");
         ligaEspa.append(" Osasuna vs Barcelona \n\n");
         ligaEspa.append(" Atlético vs Sevilla \n\n");
     }
     else if(selectedItem.equals("JORNADA 5")){
         ligaEspa.append(" Rayo vs Alavés \n\n");
         ligaEspa.append(" Athletic vs Cádiz \n\n");
         ligaEspa.append(" Valencia vs Atlético \n\n");
         ligaEspa.append(" Celta vs Mallorca \n\n");
         ligaEspa.append(" Barcelona vs Betis \n\n");
         ligaEspa.append(" Getafe vs Osasuna \n\n");
         ligaEspa.append(" Villarreal vs Almería \n\n");
         ligaEspa.append(" Sevilla vs Las Palmas \n\n");
         ligaEspa.append(" Real Madrid vs R. Sociedad \n\n");
         ligaEspa.append(" Granada vs Girona \n\n");
     }
     else if(selectedItem.equals("JORNADA 6")){
         ligaEspa.append(" Alavés vs Athletic \n\n");
         ligaEspa.append(" Girona vs Mallorca \n\n");
         ligaEspa.append(" Osasuna vs Sevilla  \n\n");
         ligaEspa.append(" Barcelona vs Celta \n\n");
         ligaEspa.append(" Almería vs Valencia \n\n");
         ligaEspa.append(" R. Sociedad vs Getafe \n\n");
         ligaEspa.append(" Rayo vs Villarreal \n\n");
         ligaEspa.append(" Las Palmas vs Granada \n\n");
         ligaEspa.append(" Betis vs Cádiz \n\n");
         ligaEspa.append(" Atlético vs Real Madrid \n\n");
     }
     else if(selectedItem.equals("JORNADA 7")){
         ligaEspa.append(" Sevilla vs Almería \n\n"); 
         ligaEspa.append(" Mallorca vs Barcelona \n\n");
         ligaEspa.append(" Athletic vs  Getafe \n\n");
         ligaEspa.append(" Real Madrid vs Las Palmas \n\n");
         ligaEspa.append(" Villareal vs Girona \n\n");
         ligaEspa.append(" Cádiz vs Rayo \n\n");
         ligaEspa.append(" Valencia vs R. Sociedad \n\n");
         ligaEspa.append(" Celta vs Alavés \n\n");
         ligaEspa.append(" Granada vs Betis \n\n");
         ligaEspa.append(" Osasuna vs Atlético \n\n");         
     }
     else if(selectedItem.equals("JORNADA 8")){
         ligaEspa.append(" Barcelona vs Sevilla \n\n");
         ligaEspa.append(" Getafe vs Villarreal \n\n");
         ligaEspa.append(" Rayo vs Mallorca \n\n");
         ligaEspa.append(" Girona vs Real Madrid \n\n");
         ligaEspa.append(" R. Sociedad vs Athletic \n\n");
         ligaEspa.append(" Almería vs Granada \n\n");
         ligaEspa.append(" Alavés vs Osasuna \n\n");
         ligaEspa.append(" Atletico vs Cádiz \n\n");
         ligaEspa.append(" Betis vs Valencia \n\n");
         ligaEspa.append(" Las Palmas vs Celta \n\n");
     }
     else if(selectedItem.equals("JORNADA 9")){
         ligaEspa.append(" Athletic vs Almería \n\n");
         ligaEspa.append(" Cádiz vs Girona  \n\n");
         ligaEspa.append(" Real Madrid vs Osasuna \n\n");
         ligaEspa.append(" Mollarca vs Valencia \n\n");
         ligaEspa.append(" Sevilla vs Rayo \n\n");
         ligaEspa.append(" Villarreal vs Las Palmas \n\n");
         ligaEspa.append(" Atlético vs R. Sociedad \n\n");
         ligaEspa.append(" Alavés vs Betis \n\n");
         ligaEspa.append(" Celta vs Getafe \n\n");
         ligaEspa.append(" Granada vs Barcelona \n\n");
     }
     else if(selectedItem.equals("JORNADA 10")){
         ligaEspa.append(" Osasuna vs Granada \n\n");
         ligaEspa.append(" R. Sociedad vs Mallorca \n\n");
         ligaEspa.append(" Getafe vs Betis \n\n");
         ligaEspa.append(" Sevilla vs Real Madrid \n\n");
         ligaEspa.append(" Celta vs Atlético \n\n");
         ligaEspa.append(" Las Palmas vs Rayo \n\n");
         ligaEspa.append(" Girona vs Almería \n\n");
         ligaEspa.append(" Villarreal vs Alavés \n\n");
         ligaEspa.append(" Barcelona vs Athlétic \n\n");
         ligaEspa.append(" Valencia vs Cádiz \n\n");     
     }
     else if(selectedItem.equals("JORNADA 11")){
         ligaEspa.append(" Girona vs Celta \n\n");
         ligaEspa.append(" Almería vs Las Palmas\n\n");
         ligaEspa.append(" Barcelona vs Real Madrid \n\n");
         ligaEspa.append(" Mallorca vs Getafe \n\n");
         ligaEspa.append(" Cádiz vs Sevilla \n\n");
         ligaEspa.append(" Betis vs Osasuna \n\n");
         ligaEspa.append(" Rayo vs R. Sociedad \n\n");
         ligaEspa.append(" Athletic vs Valencia \n\n");
         ligaEspa.append(" Atlético vs Alavés \n\n");
         ligaEspa.append(" Granada vs Vaillarreal \n\n");
     }
     else if(selectedItem.equals("JORNADA 12")){
         ligaEspa.append(" Las Palmas vs Atlético \n\n");
         ligaEspa.append(" Osasuna vs Girona \n\n");
         ligaEspa.append(" Betis vs Mallorca \n\n");
         ligaEspa.append(" Celta vs Sevilla \n\n");
         ligaEspa.append(" R. Sociedad vs Barcelona \n\n");
         ligaEspa.append(" Alavés vs Almería \n\n");
         ligaEspa.append(" Valencia vs Granda \n\n");
         ligaEspa.append(" Villarreal vs Athletic \n\n");
         ligaEspa.append(" Real Madrid vs Rayo \n\n");
         ligaEspa.append(" Getafe vs Cádiz \n\n");
     }
     else if(selectedItem.equals("JORNADA 13")){
         ligaEspa.append(" Athletic vs Celta \n\n");
         ligaEspa.append(" Rayo vs Girona \n\n");
         ligaEspa.append(" Almería vs R. Sociedad \n\n");
         ligaEspa.append(" Granada vs Getafe \n\n");
         ligaEspa.append(" Osasuna vs Las Palmas \n\n");
         ligaEspa.append(" Real Madrid vs Valencia \n\n");
         ligaEspa.append(" Barceona vs Alavés \n\n");
         ligaEspa.append(" Sevilla vs Betis \n\n");
         ligaEspa.append(" Atlérico vs Villarreal \n\n");
         ligaEspa.append(" Mallorca vs Cádiz \n\n");
     }
     else if(selectedItem.equals("JORNADA 14")){
         ligaEspa.append(" Alavés vs Granada \n\n");
         ligaEspa.append(" Rayo vs Barcelona \n\n");
         ligaEspa.append(" Valencia vs Celta \n\n");
         ligaEspa.append(" Getafe vs Almería \n\n");
         ligaEspa.append(" Atlético vs Mallorca \n\n");
         ligaEspa.append(" Villarreal vs Osasuna \n\n");
         ligaEspa.append(" R. Sociedad vs Sevilla \n\n");
         ligaEspa.append(" Cádiz vs Real Madrid \n\n");
         ligaEspa.append(" Betis vs Las Palmas \n\n");
         ligaEspa.append(" Girona vs Athletic \n\n");
     }
     else if(selectedItem.equals("JORNADA 15")){
         ligaEspa.append(" Las Palmas vs Getafe \n\n");
         ligaEspa.append(" Girona vs Valencia \n\n");
         ligaEspa.append(" Athletic vs Rayo \n\n");
         ligaEspa.append(" Real Madrid vs Granada \n\n");
         ligaEspa.append(" Osasuna vs R. Sociedad \n\n");
         ligaEspa.append(" Mallorca vs Alavés \n\n");
         ligaEspa.append(" Almería vs Betis \n\n");
         ligaEspa.append(" Sevilla vs Villarreal \n\n");
         ligaEspa.append(" Barcelona vs Atlético \n\n");
         ligaEspa.append(" Celta vs Cádiz \n\n");
     }
     else if(selectedItem.equals("JORNADA 16")){
         ligaEspa.append(" Getafe vs Valecia \n\n");
         ligaEspa.append(" Alavés vs Las Palmas \n\n");
         ligaEspa.append(" Betis vs Real Madrid \n\n");
         ligaEspa.append(" Villarreal vs R. Sociedadd \n\n");
         ligaEspa.append(" Mallorca vs Sevilla \n\n");
         ligaEspa.append(" Atlético vs Almería \n\n");
         ligaEspa.append(" Cádiz vs Osasuna \n\n");
         ligaEspa.append(" Barcelona vs Girona \n\n");
         ligaEspa.append(" Granada vs Athletic \n\n");
         ligaEspa.append(" Rayo vs Celta \n\n");
     }
     else if(selectedItem.equals("JORNADA 17")){
         ligaEspa.append(" Osasuna vs Rayo \n\n");
         ligaEspa.append(" Celta vs Granada \n\n");
         ligaEspa.append(" Athletic vs Atlético \n\n");
         ligaEspa.append(" Sevilla vs Getafe \n\n");
         ligaEspa.append(" Valencia vs Barcelona \n\n");
         ligaEspa.append(" Almería vs Mallorca \n\n");
         ligaEspa.append(" R. Sociedad vs Betis \n\n");
         ligaEspa.append(" Las Palmas vs Cádiz \n\n");
         ligaEspa.append(" Real Madrid vs Villarral \n\n");
         ligaEspa.append(" Girona vs Alavés \n\n");
     }
     else if(selectedItem.equals("JORNADA 18")){
         ligaEspa.append(" Rayo vs Valencia \n\n");
         ligaEspa.append(" Atlético vs Getafe \n\n");
         ligaEspa.append(" Granada vs Sevilla \n\n");
         ligaEspa.append(" Barcelona vs Almería \n\n");
         ligaEspa.append(" Athletic vs Las Palmas \n\n");
         ligaEspa.append(" Villarreal vs Celta \n\n");
         ligaEspa.append(" Cádiz vs R. Sociedad \n\n");
         ligaEspa.append(" Betis vs Girona \n\n");
         ligaEspa.append(" Alavéz vs Real Madrid \n\n");
         ligaEspa.append(" Mallorca vs Osasuna \n\n");
     }
     else if(selectedItem.equals("JORNADA 19")){
         ligaEspa.append(" Getafe vs Rayo \n\n");
         ligaEspa.append(" R. Sociedad vs Alavés \n\n");
         ligaEspa.append(" Valencia vs Villarreal \n\n");
         ligaEspa.append(" Granada vs Cádiz \n\n");
         ligaEspa.append(" Celta vs Betis \n\n");
         ligaEspa.append(" Real Madrid vs Mallorca \n\n");
         ligaEspa.append(" Girona vs Atlético \n\n");
         ligaEspa.append(" Osasuna vs Almería \n\n");
         ligaEspa.append(" Sevilla vs Athletic \n\n");
         ligaEspa.append(" Las Palmas vs Barcelona \n\n");
     }
     else if(selectedItem.equals("JORNADA 20")){
         ligaEspa.append(" Sevilla vs Alavés \n\n");
         ligaEspa.append(" Las Palmas vs Villarreal \n\n");
         ligaEspa.append(" Mallorca vs Celta \n\n");
         ligaEspa.append(" Athletic vs R. Sociedad\n\n");
         ligaEspa.append(" Betis vs Granada \n\n");
         ligaEspa.append(" Almería vs Girona \n\n");
         ligaEspa.append(" Cádiz vs Valencia \n\n");
         ligaEspa.append(" Barcelona vs Osasuna \n\n");
         ligaEspa.append(" Atlético vs Rayo \n\n");
         ligaEspa.append(" Getafe vs Real Madrid \n\n");
     }
     else if(selectedItem.equals("JORNADA 21")){
         ligaEspa.append(" Alavés vs Cádiz \n\n");
         ligaEspa.append(" Rayo vs Las Palmas \n\n");
         ligaEspa.append(" Villarreal vs Mallorca \n\n");
         ligaEspa.append(" Valencia vs Athletic \n\n");
         ligaEspa.append(" Celta vs R. Sociedad \n\n");
         ligaEspa.append(" Osasuna vs Getafe \n\n");
         ligaEspa.append(" Real Madrid vs Almería \n\n");
         ligaEspa.append(" Betis vs Barcelona \n\n");
         ligaEspa.append(" Girona vs Sevilla \n\n");
         ligaEspa.append(" Granada vs Atlético \n\n");
     }
     else if(selectedItem.equals("JORNADA 22")){
         ligaEspa.append(" Almería vs Alavés \n\n");
         ligaEspa.append(" R. Sociedad vs Rayo \n\n");
         ligaEspa.append(" Las Palmas vs Real Madrid \n\n");
         ligaEspa.append(" Barcelona vs Villarreal\n\n");
         ligaEspa.append(" Mallorca vs Betis\n\n");
         ligaEspa.append(" Celta vs Girona \n\n");
         ligaEspa.append(" Cádiz vs Athletic \n\n");
         ligaEspa.append(" Sevilla vs Osasuna\n\n");
         ligaEspa.append(" Atlético vs Valencia \n\n");
         ligaEspa.append(" Getafe vs Granada \n\n");
     }
     else if(selectedItem.equals("JORNADA 23")){
         ligaEspa.append(" Athletic vs Mallorca \n\n");
         ligaEspa.append(" Valencia vs Almería \n\n");
         ligaEspa.append(" Granada vs Las Palmas \n\n");
         ligaEspa.append(" Alavés vs Barcelona\n\n");
         ligaEspa.append(" Girona vs R. Sociedad \n\n");
         ligaEspa.append(" Villarreal vs Cádiz \n\n");
         ligaEspa.append(" Osasuna vs Celta \n\n");
         ligaEspa.append(" Betis vs Getafe\n\n");
         ligaEspa.append(" Real Madrid vs Atlético\n\n");
         ligaEspa.append(" Rayo vs Sevilla \n\n");
     }
     else if(selectedItem.equals("JORNADA 24")){
         ligaEspa.append(" Cádiz vs Betis \n\n");
         ligaEspa.append(" Alavés vs Villarreal \n\n");
         ligaEspa.append(" R. Sociedad vs Osasuna \n\n");
         ligaEspa.append(" Real Madrid vs Girona \n\n");
         ligaEspa.append(" Las Palmas vs Valencia\n\n");
         ligaEspa.append(" Getafe vs Celta \n\n");
         ligaEspa.append(" Mallorca vs Rayo\n\n");
         ligaEspa.append(" Sevilla vs Atlético \n\n");
         ligaEspa.append(" Barcelona vs Granada \n\n");
         ligaEspa.append(" Almería vs Athletic \n\n");
     }
     else if(selectedItem.equals("JORNADA 25")){
         ligaEspa.append(" Villarreall vs Getafe \n\n");
         ligaEspa.append(" Atlético vs Las Palmas \n\n");
         ligaEspa.append(" Osasuna vs Cádiz \n\n");
         ligaEspa.append(" Celta vs Barcelona \n\n");
         ligaEspa.append(" Valencia vs Sevilla \n\n");
         ligaEspa.append(" Rayo vs Real Madrid \n\n");
         ligaEspa.append(" Granada vs Almería \n\n");
         ligaEspa.append(" Mallorca vs R. Sociedad \n\n");
         ligaEspa.append(" Belis vs Alavés \n\n");
         ligaEspa.append(" Athletic vs Girona \n\n");
     }
     else if(selectedItem.equals("JORNADA 26")){
         ligaEspa.append(" R. Sociedad  vs Villarreal \n\n");
         ligaEspa.append(" Barcelona vs Getafe \n\n");
         ligaEspa.append(" Alavés vs Mallorca \n\n");
         ligaEspa.append(" Almería vs Atlético \n\n");
         ligaEspa.append(" Cádiz vs Celta \n\n");
         ligaEspa.append(" Bestis vs Athletic \n\n");
         ligaEspa.append(" Las Palmas vs Osasuna \n\n");
         ligaEspa.append(" Real Madrid vs Sevilla \n\n");
         ligaEspa.append(" Girona vs Rayo \n\n");
         ligaEspa.append(" Granada vs Valencia \n\n");
     }
     else if(selectedItem.equals("JORNADA 27")){
         ligaEspa.append(" Celta vs Almería \n\n");
         ligaEspa.append(" Sevilla vs R. Sociedad \n\n");
         ligaEspa.append(" Rayo vs Cádiz \n\n");
         ligaEspa.append(" Getafe vs Las Palmas \n\n");
         ligaEspa.append(" Valencia vs Real Madrid \n\n");
         ligaEspa.append(" Villarreal vs Granada \n\n");
         ligaEspa.append(" Atlético vs Betis \n\n");
         ligaEspa.append(" Mallorca vs Girona \n\n");
         ligaEspa.append(" Athletic vs Barcelona \n\n");
         ligaEspa.append(" Osasuna vs Alavés \n\n");
     }
     else if(selectedItem.equals("JORNADA 28")){
         ligaEspa.append("Barcelona  vs Mallorca \n\n");
         ligaEspa.append("Valencia  vs Getafe \n\n");
         ligaEspa.append("Cádiz  vs Atlético \n\n");
         ligaEspa.append("Granada  vs R. Sociedad \n\n");
         ligaEspa.append("Girona  vs Osasuna \n\n");
         ligaEspa.append("Alavés  vs Rayo \n\n");
         ligaEspa.append("Las Palmas  vs Athletic \n\n");
         ligaEspa.append("Real Madrid vs Celta \n\n");
         ligaEspa.append("Betis  vs Villarreal \n\n");
         ligaEspa.append(" Almería vs Sevilla \n\n");
     }
     else if(selectedItem.equals("JORNADA 29")){
         ligaEspa.append(" R. Sociedad vs Cádiz \n\n");
         ligaEspa.append(" Mallorca vs Granada \n\n");
         ligaEspa.append(" Osasuna vs Real Madrid \n\n");
         ligaEspa.append(" Getafe vs Girona \n\n");
         ligaEspa.append(" Athletic vs Alavés \n\n");
         ligaEspa.append(" Sevilla vs Celta \n\n");
         ligaEspa.append(" Las Palmas vs Almería \n\n");
         ligaEspa.append(" Villarreal vs Valencia \n\n");
         ligaEspa.append(" Rayo vs Betis \n\n");
         ligaEspa.append(" Atlético vs Barcelona \n\n");
     }
     else if(selectedItem.equals("JORNADA 30")){
         ligaEspa.append("Cádiz  vs Granada \n\n");
         ligaEspa.append("Getafe vs Sevilla \n\n");
         ligaEspa.append("Almería vs Osasuna \n\n");
         ligaEspa.append("Valencia vs Mallorca \n\n");
         ligaEspa.append("Barcelona vs Las Palmas\n\n");
         ligaEspa.append("Celta vs Rayo \n\n");
         ligaEspa.append("Girona vs Betis \n\n");
         ligaEspa.append("Alavés vs R. Sociedad \n\n");
         ligaEspa.append("Real Madrid vs Athletic \n\n");
         ligaEspa.append("Villarreal vs Atlético \n\n");
     }
     else if(selectedItem.equals("JORNADA 31")){
         ligaEspa.append("Betis vs Celta \n\n");
         ligaEspa.append("Atlético vs Girona \n\n");
         ligaEspa.append("Rayo vs Getafe \n\n");
         ligaEspa.append("Mallorca vs Real Madrid \n\n");
         ligaEspa.append("Cádiz vs Barcelona \n\n");
         ligaEspa.append("Las Palmas vs Sevilla \n\n");
         ligaEspa.append("Granada vs Alavés \n\n");
         ligaEspa.append("Athletic vs Villarreal \n\n");
         ligaEspa.append("R. Sociedad vs Almería \n\n");
         ligaEspa.append(" Osasuna vs Valencia \n\n");
     }
     else if(selectedItem.equals("JORNADA 32")){
         ligaEspa.append(" Athletic vs Granada \n\n");
         ligaEspa.append(" Celta vs Las Palmas \n\n");
         ligaEspa.append(" Rayo vs Osasuna\n\n");
         ligaEspa.append(" Valencia vs Betis \n\n");
         ligaEspa.append(" Girona vs Cádiz \n\n");
         ligaEspa.append(" Getafe vs R. Sociedad \n\n");
         ligaEspa.append(" Almería vs Villarreal \n\n");
         ligaEspa.append(" Alavés vs Atlético \n\n");
         ligaEspa.append(" Real Madrid vs Barcelona \n\n");
         ligaEspa.append(" Sevilla vs Mallorca \n\n");
     }
     else if(selectedItem.equals("JORNADA 33")){
         ligaEspa.append(" Almería vs Getafe \n\n");
         ligaEspa.append(" Barcelona vs Valencia \n\n");
         ligaEspa.append(" Alavés vs Celta \n\n");
         ligaEspa.append(" Atlético vs Athletic \n\n");
         ligaEspa.append(" R. Sociedad vs Real Madrid \n\n");
         ligaEspa.append(" Cádiz vs Mallorca \n\n");
         ligaEspa.append(" Granada vs Osasuna \n\n");
         ligaEspa.append(" Villarreal vs Rayo \n\n");
         ligaEspa.append(" Betis vs Sevilla \n\n");
         ligaEspa.append(" Las Palmas vs Girona \n\n");
     }
     else if(selectedItem.equals("JORNADA 34")){
         ligaEspa.append(" Celta vs Villarreal \n\n");
         ligaEspa.append(" Getafe vs Athletic \n\n");
         ligaEspa.append(" Girona vs Barcelona \n\n");
         ligaEspa.append(" Mallorca vs Atlético \n\n");
         ligaEspa.append(" Osasuna vs Betis \n\n");
         ligaEspa.append(" Rayo vs Almería \n\n");
         ligaEspa.append(" Real Madrid vs Cádiz \n\n");
         ligaEspa.append(" R. Sociedad vs Las Palmas \n\n");
         ligaEspa.append(" Sevilla vs Granada \n\n");
         ligaEspa.append(" Valencia vs Alavés \n\n");
     }
     else if(selectedItem.equals("JORNADA 35")){
         ligaEspa.append(" Alavés vs Girona \n\n");
         ligaEspa.append(" Athletic vs Osasuna \n\n");
         ligaEspa.append(" Atlético vs Celta \n\n");
         ligaEspa.append(" Barcelona vs R. Sociedad \n\n");
         ligaEspa.append(" Cádiz vs Getafe \n\n");
         ligaEspa.append(" Granada vs Real Madrid \n\n");
         ligaEspa.append(" Mallorca vs Las Palmas \n\n");
         ligaEspa.append(" Betis vs Almería \n\n");
         ligaEspa.append(" Valencia vs Rayo \n\n");
         ligaEspa.append(" Villarreal vs Sevilla \n\n");
     }
     else if(selectedItem.equals("JORNADA 36")){
         ligaEspa.append(" Almería vs Barcelona \n\n");
         ligaEspa.append(" Celta vs Athletic\n\n");
         ligaEspa.append(" Getafe vs Atlético \n\n");
         ligaEspa.append(" Girona vs Villarreal \n\n");
         ligaEspa.append(" Las Palmas vs Betis \n\n");
         ligaEspa.append(" Osasuna vs Mallorca \n\n");
         ligaEspa.append(" Rayo vs Granada \n\n");
         ligaEspa.append(" Real Madrid vs Alavés \n\n");
         ligaEspa.append(" R. Sociedad vs Valencia \n\n");
         ligaEspa.append(" Sevilla vs Cádiz \n\n");
     }
     else if(selectedItem.equals("JORNADA 37")){
         ligaEspa.append(" Alavés vs Getafe \n\n");
         ligaEspa.append(" Athletic vs Sevilla \n\n");
         ligaEspa.append(" Atlético vs Osasuna \n\n");
         ligaEspa.append(" Barcelona vs Rayo \n\n");
         ligaEspa.append(" Cádiz vs Las Palmas \n\n");
         ligaEspa.append(" Granada vs Celta \n\n");
         ligaEspa.append(" Mallorca vs Almería \n\n");
         ligaEspa.append(" Betis vs R. Sociedad \n\n");
         ligaEspa.append(" Valencia vs Girona \n\n");
         ligaEspa.append(" Villarreal vs Real Madrid \n\n");
     }
     else if(selectedItem.equals("JORNADA 38")){
         ligaEspa.append(" Almería vs Cádiz \n\n");
         ligaEspa.append(" Celta vs Valencia\n\n");
         ligaEspa.append(" Getafe vs Mallorca \n\n");
         ligaEspa.append(" Girona vs Granada \n\n");
         ligaEspa.append(" Las Palmas vs Alavés \n\n");
         ligaEspa.append(" Osasuna vs Villarreal \n\n");
         ligaEspa.append(" Rayo vs Athletic \n\n");
         ligaEspa.append(" Real Madrid vs Betis \n\n");
         ligaEspa.append(" R. Sociedad vs Atlético \n\n");
         ligaEspa.append(" Sevilla vs Barcelona \n\n");
     }
     
    }//GEN-LAST:event_cbEspaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vLigaEspa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vLigaEspa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vLigaEspa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vLigaEspa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vLigaEspa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEspa;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.ButtonGroup grupo10;
    private javax.swing.ButtonGroup grupo2;
    private javax.swing.ButtonGroup grupo3;
    private javax.swing.ButtonGroup grupo4;
    private javax.swing.ButtonGroup grupo5;
    private javax.swing.ButtonGroup grupo6;
    private javax.swing.ButtonGroup grupo7;
    private javax.swing.ButtonGroup grupo8;
    private javax.swing.ButtonGroup grupo9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblNombre;
    private javax.swing.JTextArea ligaEspa;
    // End of variables declaration//GEN-END:variables
}
