package Vistas;


import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;


import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ajgem
 */
public class vQuiniela extends javax.swing.JFrame {

    /**
     * Creates new form vQuiniela
     */
    public vQuiniela() {
       // this. setLocationRelativeTo(null);
       
        
        initComponents();
         ligaNac.setEditable(false);//EL TEXTAREA NO SE PODRA EDITAR
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        bg3 = new javax.swing.ButtonGroup();
        bg4 = new javax.swing.ButtonGroup();
        bg5 = new javax.swing.ButtonGroup();
        bg6 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rb18 = new javax.swing.JRadioButton();
        rb16 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb11 = new javax.swing.JRadioButton();
        rb12 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        rb14 = new javax.swing.JRadioButton();
        rb15 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb13 = new javax.swing.JRadioButton();
        rb17 = new javax.swing.JRadioButton();
        guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ligaNac = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CboxCategorias = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(54, 54, 54));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));

        bg6.add(rb18);
        rb18.setText("2");

        bg6.add(rb16);
        rb16.setText("1");

        bg1.add(rb1);
        rb1.setText("1");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        bg2.add(rb6);
        rb6.setText("2");

        bg2.add(rb4);
        rb4.setText("1");

        bg3.add(rb8);
        rb8.setText("X");

        bg3.add(rb9);
        rb9.setText("2");

        bg3.add(rb7);
        rb7.setText("1");

        bg4.add(rb11);
        rb11.setText("X");

        bg4.add(rb12);
        rb12.setText("2");

        bg4.add(rb10);
        rb10.setText("1");

        bg5.add(rb14);
        rb14.setText("X");

        bg5.add(rb15);
        rb15.setText("2");

        bg1.add(rb2);
        rb2.setText("X");

        bg1.add(rb3);
        rb3.setText("2");

        bg2.add(rb5);
        rb5.setText("X");

        bg5.add(rb13);
        rb13.setText("1");

        bg6.add(rb17);
        rb17.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb6)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb2)
                    .addComponent(rb3)
                    .addComponent(rb1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb4)
                    .addComponent(rb5)
                    .addComponent(rb6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb7)
                    .addComponent(rb8)
                    .addComponent(rb9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb10)
                    .addComponent(rb11)
                    .addComponent(rb12))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb13)
                    .addComponent(rb14)
                    .addComponent(rb15))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb16)
                    .addComponent(rb17)
                    .addComponent(rb18))
                .addContainerGap())
        );

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        ligaNac.setColumns(20);
        ligaNac.setRows(5);
        jScrollPane1.setViewportView(ligaNac);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LIGA NACIONAL");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUINIELA DEPORTIVA");

        CboxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JORNADA 1", "JORNADA 2", "JORNADA 3", "JORNADA 4", "JORNADA 5", "JORNADA 6", "JORNADA 7", "JORNADA 8", "JORNADA 9", "JORNADA 10", "JORNADA 4 ATRASADA", "JORNADA 11", "JORNADA 12", "JORNADA 13", "JORNADA 11 ATRASADA", "JORNADA 12 ATRASADA", "JORNADA 14 ", "JORNADA 15", "JORNADA 16" }));
        CboxCategorias.setToolTipText("");
        CboxCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxCategoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardar)
                    .addComponent(CboxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)
                        .addGap(236, 236, 236))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1)
                        .addGap(0, 262, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addComponent(CboxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardar)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxCategoriasActionPerformed
        // TODO add your handling code here:
     String selectedItem = (String) CboxCategorias.getSelectedItem();//Esta línea de código obtiene el elemento seleccionado actualmente en un componente gráfico llamado CboxCategorias
     ligaNac.setText("");//Esta línea de código está limpiando (estableciendo a una cadena vacía) el contenido del área de texto ligaNac.
     if (selectedItem.equals("JORNADA 1")) {//Esta línea establece una condición. La condición evalúa si el valor de selectedItem es igual a la cadena 
    ligaNac.append(" Antigua GFC vs Achuapa\n\n");//Esta linea setea lo que esta dentro del if, evaulua la condicion del valor
    ligaNac.append(" Municipal vs Guastatoya\n\n");
    ligaNac.append(" Comuniaciones vs Xinabajul\n\n");
    ligaNac.append(" Malacateco vs Xelajú MC\n\n");
    ligaNac.append(" Coatepeque vs Cobán Imperial\n\n");
    ligaNac.append(" Zacapa vs Mixco\n\n");
    
    //se ingresan todos los datos de las jornadas
        } else if (selectedItem.equals("JORNADA 2")) {
    ligaNac.append(" Guastatoya vs Zacapa\n\n");
    ligaNac.append(" Cobán Imperial vs Malacateco\n\n");
    ligaNac.append(" Xelajú MC vs Camunicaciones\n\n");
    ligaNac.append(" Mixco vs Antigua GFC\n\n");
    ligaNac.append(" Achuapa vs Municipal\n\n");
    ligaNac.append(" Xinabajul vs Coatepeque\n\n");
    
        } else if(selectedItem.equals("JORNADA 3")) {
    ligaNac.append(" Municipal vs Antigua GFC\n\n");
    ligaNac.append(" Guastatoya vs Mixco\n\n");
    ligaNac.append(" Zacapa vs Achuapa\n\n");
    ligaNac.append(" Comunicaciones vs Coban Imperial\n\n");
    ligaNac.append(" Xelaju MC vs Xinabajul\n\n");
    ligaNac.append(" Malacateco vs Coatepeque\n\n");
    
        }else if (selectedItem.equals("JORNADA 4")){
    ligaNac.append(" Municipal vs Mixco\n\n");
    ligaNac.append(" Antigua GFC vs Zacapa\n\n");
    ligaNac.append(" Coban Imperial vs Xelaju MC\n\n");
    ligaNac.append(" Comunicaciones vs Coban Imperial\n\n");
    ligaNac.append(" Achuapa vs Guastatoya\n\n");
    ligaNac.append(" Malacateco vs Xinabajul\n\n");
            
        }else if(selectedItem.equals("JORNADA 5")){
    ligaNac.append("  Mixco vs Achuapa\n\n");
    ligaNac.append("  Comunicaciones vs Malacateco\n\n");
    ligaNac.append("  Zacapa vs Municipal\n\n");
    ligaNac.append("  Guastatoya vs Antigua GFC\n\n");
    ligaNac.append("  Xinabajul vs Coban Imperial\n\n");
    ligaNac.append("  Xelaju MC vs Coatepeque\n\n");   
        
        }else if(selectedItem.equals("JORNADA 6")){
    ligaNac.append("  Mixco vs Zacapa\n\n");
    ligaNac.append("  Coban Imperial vs Coatepeque\n\n");
    ligaNac.append("  Xelaju MC vs Malacateco\n\n");
    ligaNac.append("  Achuapa vs Antigua GFC\n\n");
    ligaNac.append("  Guastatoya vs Municipal\n\n");
    ligaNac.append("  Xinabajul vs Comunicaciones\n");   
           
        }else if (selectedItem.equals("JORNADA 7")){
    ligaNac.append("   Malacateco vs Coban Imperial\n\n");
    ligaNac.append("   Municipal vs Achuapa\n\n");
    ligaNac.append("   Comunicaciones vs Xelaju MC\n\n");
    ligaNac.append("   Antigua GFC vs Mixco\n\n");
    ligaNac.append("   Zacapa vs Guastatoya\n\n");
    ligaNac.append("   Coatepeque vs Xinabajul\n");  
    
        }else if (selectedItem.equals("JORNADA 8")){
    ligaNac.append("   Coban Imperial vs Comunicaciones\n\n");
    ligaNac.append("   Coatepeque vs Malacateco\n\n");
    ligaNac.append("   Mixco vs Guastatoya\n\n");
    ligaNac.append("   Xinabajul vs Xelaju MC\n\n");
    ligaNac.append("   Antigua GFC vs Municipal\n\n");
    ligaNac.append("   Achuapa vs Zacapa\n");  
        
        }else if (selectedItem.equals("JORNADA 9")){
    ligaNac.append("   Mixco vs Municipal\n\n");
    ligaNac.append("   Comunicaciones vs Coatepeque\n\n");
    ligaNac.append("   Xelaju MC vs Coban Imperial\n\n");
    ligaNac.append("   Guastatoya vs Achuapa\n\n");
    ligaNac.append("   Zacapa vs Antigua GFC\n\n");
    ligaNac.append("   Xinabajul vs Malacateco\n");  
    
        }else if (selectedItem.equals("JORNADA 10")){
    ligaNac.append("   Municipal vs Zacapa\n\n");
    ligaNac.append("   Antigua GFC vs Guastatoya\n\n");
    ligaNac.append("   Malacateco vs Comunicaciones\n\n");
    ligaNac.append("   Coban Imperial vs Xinabajul\n\n");
    ligaNac.append("   Coatepeque vs Xelaju MC\n\n");
    ligaNac.append("   Achuapa vs Mixco\n");  
    
        }else if (selectedItem.equals("JORNADA 4 ATRASADA")){
    ligaNac.append(" Coatepeque vs Comunicaciones \n\n");
            
        }else if(selectedItem.equals("JORNADA 11")){
    ligaNac.append("   Antigua GFC vs Coatepeque\n\n");
    ligaNac.append("   Mixco vs Xinabajul\n\n");
    ligaNac.append("   Guastatoya vs Xelaju MC\n\n");
    ligaNac.append("   Achuapa vs Coban Imperial\n\n");
    
        }else if(selectedItem.equals("JORNADA 12")){
    ligaNac.append("    Malacateco vs Antigua GFC\n\n");
    ligaNac.append("    Coban Imperial vs Zacapa\n\n");
    ligaNac.append("    Coatepeque vs Mixco\n\n");
    ligaNac.append("    Xinabajul vs Guastatoya\n\n");
        
        }else if(selectedItem.equals("JORNADA 13")){
    ligaNac.append("   Achuapa vs Xinabajul\n\n");
    ligaNac.append("   Antigua GFC vs Comunicaciones\n\n");
    ligaNac.append("   Zacapa vs Xelaju MC\n\n");
    ligaNac.append("   Municipal vs Coban Imperial\n\n");
    ligaNac.append("   Guastatoya vs Coatepeque\n\n");
    ligaNac.append("   Mixco vs Malacateco\n");  
   
        
 }else if (selectedItem.equals("JORNADA 14 ")){
   
    ligaNac.append("   Malacateco vs Guastatoya\n\n");
    ligaNac.append("   Coban Imperial vs Antigua GFC\n\n");
    ligaNac.append("   Comunicaciones vs Mixco\n\n");
    ligaNac.append("   Xelaju MC vs Municipal\n\n");
    ligaNac.append("   Coatepeque vs Achuapa\n\n");
    ligaNac.append("   Xinabajul vs Zacapa\n");  
 
 }else if (selectedItem.equals("JORNADA 15")){
    ligaNac.append("   Municipal vs Xinabajul\n\n");
    ligaNac.append("   Mixco vs Coban Imperial\n\n");
    ligaNac.append("   Antigua GFC vs Xelaju MC\n\n");
    ligaNac.append("   Zacapa vs Coatepeque\n\n");
    ligaNac.append("   Achuapa vs Malacateco\n\n");
    ligaNac.append("   Guastatoya vs Comunicaciones\n");  
     
 }else if (selectedItem.equals("JORNADA 16")){
    ligaNac.append("   Coatepeque vs Municipal\n\n");
    ligaNac.append("   Coban Imperial vs Guastatoya\n\n");
    ligaNac.append("   Comunicaciones vs Achuapa\n\n");
    ligaNac.append("   Malacateco vs Zacapa\n\n");
    ligaNac.append("    Xelaju MC vs Mixco\n\n");
    ligaNac.append("   Xinabajul vs Antigua GFC\n");  
     
 }else if (selectedItem.equals("JORNADA 11 ATRASADA")){
    ligaNac.append("  Zacapa vs Comunicaciones \n\n");
    ligaNac.append("  Municipal vs Malacateco \n\n");    
 
    
 }else if (selectedItem.equals("JORNADA 12 ATRASADA")){
    ligaNac.append("   Xelaju MC vs Achuapa \n\n");
    ligaNac.append(" Comunicaciones vs Municipal \n\n");    
        
 }
     
    }//GEN-LAST:event_CboxCategoriasActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
   // TODO add your handling code here:
         String seleccion = "";//Esto inicializa una variable de tipo String llamada seleccion con una cadena vacía
        if (rb1.isSelected()) {//El código verifica si alguno de los botones de radio rb1, rb2 o rb3 está seleccionado (isSelected()).
            seleccion = rb1.getText();//Se obtiene la seleccion del radiobutton
        } else if (rb2.isSelected()) {//si no se obtiene la seleccion de otro radio button
            seleccion = rb2.getText();
        } else if (rb3.isSelected()) {
            seleccion = rb3.getText();
        }
        if (rb4.isSelected()) {
            seleccion = rb4.getText();
        } else if (rb5.isSelected()) {
            seleccion = rb5.getText();
        } else if (rb6.isSelected()) {
            seleccion = rb6.getName();
        }


        // Guardar la selección en un archivo de texto
        try (PrintWriter writer = new PrintWriter(new FileWriter("seleccion.txt"))) {
            writer.println("Selección del usuario:");
         writer.println(seleccion/*+ligaNac.getText()*/);
            //writer.println("Texto ingresado en el JTextArea:");
         //   writer.println(ligaNac.getText());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    

        
    }//GEN-LAST:event_guardarActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vQuiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vQuiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vQuiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vQuiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new vQuiniela().setVisible(true);//: Esta parte del código crea un nuevo objeto de la clase vQuiniela
               //Después de crear la instancia de vQuiniela, el método setVisible(true) se invoca en ella. 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxCategorias;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.ButtonGroup bg3;
    private javax.swing.ButtonGroup bg4;
    private javax.swing.ButtonGroup bg5;
    private javax.swing.ButtonGroup bg6;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblNombre;
    private javax.swing.JTextArea ligaNac;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb13;
    private javax.swing.JRadioButton rb14;
    private javax.swing.JRadioButton rb15;
    private javax.swing.JRadioButton rb16;
    private javax.swing.JRadioButton rb17;
    private javax.swing.JRadioButton rb18;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    // End of variables declaration//GEN-END:variables
}
